# Project Properties
sonar.projectKey=com.appiancs.plugins:chartgenie
sonar.projectName=ChartGenie
sonar.ws.timeout=3000
sonar.qualitygate.wait=true
sonar.findbugs.timeout=6000000

# Language-Independent Properties
sonar.sources=src/main
sonar.tests=src/test

# Java Properties
sonar.java.binaries=build/classes/java/main
sonar.coverage.jacoco.xmlReportPaths=build/jacoco/jacoco.xml
